Basics of Numpy:

    NumPy is one of the fundamental packages for scientific computing in Python. It contains functionality for multidimensional arrays, high-level mathematical func‐ tions such as linear algebra operations and the Fourier transform, and pseudorandom number generators.

Why Numpy?


    - NumPy arrays are faster and more compact than Python lists.

    - NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

    - An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a     mechanism of specifying the data types.

In [28]:
import numpy as np



1. Array with the ranges of the element:

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [30]:
np.arange(4,dtype=np.float32)  # range with specified data type


array([0., 1., 2., 3.], dtype=float32)



2.Linespaces (start,end,intervals):

In [38]:
np.linspace(0,10,5)  #create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.linspace(0,10,5,dtype=np.int64)  # with Specified the data type


array([ 0,  2,  5,  7, 10])



3.The important attributes of an ndarray object are:


In [49]:
a=np.arange(6).reshape(3,2) #new shape to an array using rows and columns
a #print(a)


array([[0, 1],
       [2, 3],
       [4, 5]])

3.1 ndarray.ndim:
    The number of axes (dimensions) of the array.

In [52]:
a.ndim

2

3.2 ndarray.shape::
    The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

In [51]:
a.shape

(3, 2)

3.3 ndarray.size:
    The total number of elements of the array. This is equal to the product of the elements of shape. 

In [53]:
a.size

6

3.4 ndarray.dtype:
    An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [54]:
a.dtype

dtype('int64')

3.5 ndarray.itemsize:
    The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [56]:
a.itemsize

8

3.6 ndarray.data:
    The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [58]:
a.data