Basics of Numpy:

    NumPy is one of the fundamental packages for scientific computing in Python. It contains functionality for multidimensional arrays, high-level mathematical functions such as linear algebra operations and the Fourier transform, and pseudorandom number generators.

Why Numpy?


    - NumPy arrays are faster and more compact than Python lists.

    - NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

    - An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.

In [5]:
import numpy as np



1. Array with the ranges of the element:

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [30]:
np.arange(4,dtype=np.float32)  # range with specified data type


array([0., 1., 2., 3.], dtype=float32)



2.Linespaces (start,end,intervals):

In [38]:
np.linspace(0,10,5)  #create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.linspace(0,10,5,dtype=np.int64)  # with Specified the data type


array([ 0,  2,  5,  7, 10])



3.The important attributes of an ndarray object are:


In [11]:
a=np.arange(6).reshape(3,2) #new shape to an array using rows and columns and invalid range cannot be reshaped
a #print(a)


array([[0, 1],
       [2, 3],
       [4, 5]])


3.1 ndarray.ndim:
    The number of axes (dimensions) of the array.

In [52]:
a.ndim

2


3.2 ndarray.shape::
    The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

In [51]:
a.shape

(3, 2)


3.3 ndarray.size:
    The total number of elements of the array. This is equal to the product of the elements of shape. 

In [53]:
a.size

6


3.4 ndarray.dtype:
    An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [54]:

a.dtype

dtype('int64')


3.5 ndarray.itemsize:
    The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [12]:
a.itemsize

8


3.6 ndarray.data:
    The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [13]:
a.data

4.Array with zeros

In [16]:
np.zeros(2) #creates a row matrix with given number of elements
np.zeros((2,3)) # creates a matrix of 2*3

array([[0., 0., 0.],
       [0., 0., 0.]])


5. Array with ones
same like zeros

In [18]:
np.ones(3)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])


6. Empty array

In [27]:
np.empty(5) #creates a empty array of given size which holds a garbage value in a row matrix
np.empty((2,3))  #2*3 empty matrix

array([[1., 1., 1.],
       [1., 1., 1.]])


7. Trigonometric functions

In [29]:
from numpy import pi
x=np.linspace(0,3*pi,20)
f=np.sin(x)  # angle is in radian
f

array([ 0.00000000e+00,  4.75947393e-01,  8.37166478e-01,  9.96584493e-01,
        9.15773327e-01,  6.14212713e-01,  1.64594590e-01, -3.24699469e-01,
       -7.35723911e-01, -9.69400266e-01, -9.69400266e-01, -7.35723911e-01,
       -3.24699469e-01,  1.64594590e-01,  6.14212713e-01,  9.15773327e-01,
        9.96584493e-01,  8.37166478e-01,  4.75947393e-01,  3.67394040e-16])


8. Matrix multilication

In [9]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
a*b             # elementwise matrix multiplication
a@b             # matrix multiplication
a.dot(b)        # another way of matrix multiplication

array([[19, 22],
       [43, 50]])


8. Random numbers


In [65]:
r=np.random.default_rng(1) # instance of defualt random number denerator
a=np.ones((2,3),dtype=int)      # Initially it will be float
b=r.random((2,3))
a*=3
a
b+=a  # this can be done
b
a+=b    # b is not automatically converted to integer type
a

TypeError: 'numpy.ndarray' object is not callable