Basics of Numpy:

    NumPy is one of the fundamental packages for scientific computing in Python. It contains functionality for multidimensional arrays, high-level mathematical functions such as linear algebra operations and the Fourier transform, and pseudorandom number generators.

Why Numpy?



    - NumPy arrays are faster(optimizations written in C) and more      compact than Python lists.

    - Vectorizationn via broadcasting(Avoiding loops).

    - NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.

    - An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.
    - ML finds patterns in numpy array

In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
#Numpy's main datatype is nd-array
a1=np.array([1,2,3])    
a1
#Array ,vector
#1-dim.
#shape (1,3)

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,3,3,4],[2,3,4,1]])  
a2
#Array , matrix
# more than 1-dim.
#shape (2,4)

array([[1, 3, 3, 4],
       [2, 3, 4, 1]])

In [5]:
a3=np.array([[[10,20,30],
            [40,50,60]],

            [[2.3,4.5,6.4],
            [3.4,5.6,7.8]],
            
            [[1,2,3],
            [4,5,6]]]

)       
a3       
#Array , matrix                          
#more than 1- dim
#shape (3,2,3)  (rows,column,ndim)

array([[[10. , 20. , 30. ],
        [40. , 50. , 60. ]],

       [[ 2.3,  4.5,  6.4],
        [ 3.4,  5.6,  7.8]],

       [[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]]])

In [6]:
#Shape
a1.shape,a3.shape   


((3,), (3, 2, 3))

In [7]:
#NUmber of dimension
a1.ndim,a2.ndim,a3.ndim     

(1, 2, 3)

In [8]:
#Data types:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [9]:
#Number of elements in an array
a1.size,a2.size

(3, 8)

In [10]:
#Type of the array
type(a1),type(a3) #ndarray is a universal data type

(numpy.ndarray, numpy.ndarray)

In [11]:
#Creating a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2  3
0  1  3  3  4
1  2  3  4  1

In [12]:
df.dtypes

0    int64
1    int64
2    int64
3    int64
dtype: object



3.The important attributes of an ndarray object are:


In [13]:
a=np.array([[0, 1],
       [2, 3],
       [4, 5]])
a

array([[0, 1],
       [2, 3],
       [4, 5]])


3.1     .ndim:
    The number of axes (dimensions) of the array.

In [14]:
a.ndim

2


3.2 .shape::
    The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

In [15]:
a.shape

(3, 2)


3.3 .size:
    The total number of elements of the array. This is equal to the product of the elements of shape. 

In [16]:
a.size

6


3.4 .dtype:
    An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [17]:

a.dtype

dtype('int64')


3.5 .itemsize:
    The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [18]:
a.itemsize

8


3.6 .data:
    The buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [19]:
a.data

# Creating Arrays

In [20]:
# 1-D array
sample_array=np.array([1,2,3])  
sample_array

array([1, 2, 3])

In [21]:
#Creates 2x3 matrix containing ones only
ones=np.ones((2,3))     
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#Create sa 3*3 numpy array with zeros in it:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
#arange(start,stop,step=1(default))
range_array=np.arange(0,10,2) #same like the range but called as array of range i.e arange
range_array

array([0, 2, 4, 6, 8])

In [25]:
#Random numbers array
#randint(low,high=None,size=None,dtype='1')
# low to high is the number ingeters between them 
#Size is the shape of the numpy array
random_array=np.random.randint(0,10,size=(3,4)) 
random_array

array([[4, 5, 6, 1],
       [9, 0, 9, 9],
       [4, 1, 9, 2]])

In [26]:
random_array2=np.random.random((2,3))   #Returns the random floats from 0.0 to 1.0
random_array2

array([[0.34498473, 0.89322798, 0.60964587],
       [0.67499394, 0.9390702 , 0.84605961]])

In [27]:
#rand(d0,d1,d2......dn)
random_array3=np.random.rand(5,3)   #Quike similar to random.random
random_array3

array([[0.29660781, 0.06795067, 0.07213856],
       [0.2956857 , 0.30130727, 0.82415627],
       [0.53291078, 0.34666734, 0.44673754],
       [0.06340927, 0.03538464, 0.62180122],
       [0.64656691, 0.06503493, 0.01180755]])

# But 
    the random number in numpy is they aren't actually random, they are set with random seed 
    They are pseudo-random numbers.
    What if we share the same code or a file? Does this random numbers will be same?NO.
    Each time there will a different number
SO there comes numpy random seed()
    

In [28]:
np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(3,4))
random_array4
# seed function makes the created random numbers aligned with the seed

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [29]:
np.random.seed(seed=0)
random_array5=np.random.random((5,4))
random_array5

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

# Viewing arrays and matrices

In [44]:
# Finding the unique number in an array
np.unique(random_array)

array([0, 1, 2, 4, 5, 6, 9])

In [47]:
a1

array([1, 2, 3])

In [48]:
a2

array([[1, 3, 3, 4],
       [2, 3, 4, 1]])

In [46]:
a3

array([[[10. , 20. , 30. ],
        [40. , 50. , 60. ]],

       [[ 2.3,  4.5,  6.4],
        [ 3.4,  5.6,  7.8]],

       [[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]]])

In [110]:
a3.shape

(3, 2, 3)

In [50]:
a1[0]

1

In [109]:
a2[:2,:3]

array([[1, 3, 3],
       [2, 3, 4]])

In [56]:
a3[0]

array([[10., 20., 30.],
       [40., 50., 60.]])

In [57]:
a3[1]

array([[2.3, 4.5, 6.4],
       [3.4, 5.6, 7.8]])

In [100]:
a3[:3,:1,:2]

array([[[10. , 20. ]],

       [[ 2.3,  4.5]],

       [[ 1. ,  2. ]]])

In [30]:
#create 2x2 numpy array with diagonals 1 otherwise 0
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#Create a numpy array with 20 random integers between 1 -100:
arr=np.arange(10)
even=arr[arr%2==0]
print(even)


[0 2 4 6 8]


In [32]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.diag(arr))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]



1. Array with the ranges of the element:

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
np.arange(4,dtype=np.float32)  # range with specified data type


array([0., 1., 2., 3.], dtype=float32)



2.Linespaces (start,end,intervals):

In [35]:
np.linspace(0,10,5)  #create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0,10,5,dtype=np.int64)  # with Specified the data type


array([ 0,  2,  5,  7, 10])

4.Array with zeros

In [37]:
np.zeros(2) #creates a row matrix with given number of elements
np.zeros((2,3)) # creates a matrix of 2*3

array([[0., 0., 0.],
       [0., 0., 0.]])


5. Array with ones
same like zeros

In [38]:
np.ones(3)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])


6. Empty array

In [39]:
np.empty(5) #creates a empty array of given size which holds a garbage value in a row matrix
np.empty((2,3))  #2*3 empty matrix

array([[1., 1., 1.],
       [1., 1., 1.]])


7. Trigonometric functions

In [40]:
from numpy import pi
x=np.linspace(0,3*pi,20)
f=np.sin(x)  # angle is in radian
f

array([ 0.00000000e+00,  4.75947393e-01,  8.37166478e-01,  9.96584493e-01,
        9.15773327e-01,  6.14212713e-01,  1.64594590e-01, -3.24699469e-01,
       -7.35723911e-01, -9.69400266e-01, -9.69400266e-01, -7.35723911e-01,
       -3.24699469e-01,  1.64594590e-01,  6.14212713e-01,  9.15773327e-01,
        9.96584493e-01,  8.37166478e-01,  4.75947393e-01,  3.67394040e-16])


8. Matrix multilication

In [41]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
a*b             # elementwise matrix multiplication
a@b             # matrix multiplication
a.dot(b)        # another way of matrix multiplication

array([[19, 22],
       [43, 50]])


8. Random numbers
