# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [9]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()
array1d=np.array([1,2,3])
array1d.ndim
# Create a 2-dimensional NumPy array using np.array()
array2d=np.array([[1,2,3],
                [4,4,6]])
array2d.ndim
# Create a 3-dimensional Numpy array using np.array()
array3d=np.array([[[1,2,3],
                [4,4,6]],

                [[1,2,3],
                [4,4,6]]])
array3d.ndim,array3d.shape

(3, (2, 2, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Attributes of array (shape, number of dimensions, data type, size )
array3d.ndim,array3d.shape,array3d.dtype,array3d.size,type(array3d)


(3, (2, 2, 3), dtype('int64'), 12, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
numbers = pd.DataFrame(array2d,columns=["Zero","One","Two"])    # Can also give index
numbers

Zero  One  Two
0     1    2    3
1     4    4    6

In [17]:
# Create an array of shape (10, 2) with only ones
ones_array=np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array=np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
array_range=np.arange(0,100,3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array1=np.random.randint(0,10,size=(7,2))
random_array1

array([[3, 8],
       [0, 4],
       [1, 4],
       [0, 8],
       [1, 2],
       [6, 3],
       [0, 7]])

In [30]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_array2=np.random.rand(3,5)
random_array2

array([[0.86805705, 0.82917745, 0.62388574, 0.76648531, 0.96495146],
       [0.13759338, 0.68838856, 0.63185697, 0.29894469, 0.4738647 ],
       [0.29006843, 0.77716183, 0.96033587, 0.63865261, 0.36452062]])

In [32]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3=np.random.randint(0,10,size=(4,6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [47]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array3=np.random.randint(1,10,size=(3,7))
random_array3

# Find the unique numbers in the array you just created
np.unique(random_array3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Find the 0'th index of the latest array you created
random_array3[0]

array([6, 7, 4, 7, 8, 1, 6])

In [49]:
# Get the first 2 rows of latest array you created
random_array3[:2]

array([[6, 7, 4, 7, 8, 1, 6],
       [8, 5, 4, 2, 6, 6, 1]])

In [50]:
random_array3

array([[6, 7, 4, 7, 8, 1, 6],
       [8, 5, 4, 2, 6, 6, 1],
       [9, 6, 3, 4, 4, 3, 3]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array
random_array3[:2,:2]

array([[6, 7],
       [8, 5]])

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array4=np.random.randint(0,10,size=(3,5))

array_ones=np.ones((3,5))


In [58]:
# Add the two arrays together
random_array4 + array_ones

array([[4., 8., 8., 7., 3.],
       [1., 1., 3., 6., 7.],
       [6., 6., 6., 3., 6.]])

In [60]:
# Create another array of ones of shape (5, 3)
array_ones2=np.ones((5,3))
array_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# Try add the array of ones and the other most recent array together
random_array4 + array_ones2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [64]:
# Fixing above broadcasting problem  (3,5) * (3,5)
random_array4 + array_ones2.T

array([[4., 8., 8., 7., 3.],
       [1., 1., 3., 6., 7.],
       [6., 6., 6., 3., 6.]])

In [66]:
# Subtract the new array of ones from the other most recent array
random_array4 - array_ones2.T

array([[ 2.,  6.,  6.,  5.,  1.],
       [-1., -1.,  1.,  4.,  5.],
       [ 4.,  4.,  4.,  1.,  4.]])

In [68]:
# Multiply the ones array with the latest array
random_array4 * array_ones2.T

array([[3., 7., 7., 6., 2.],
       [0., 0., 2., 5., 6.],
       [5., 5., 5., 2., 5.]])

In [70]:
# Take the latest array to the power of 2 using '**'
random_array4 **2

array([[ 9, 49, 49, 36,  4],
       [ 0,  0,  4, 25, 36],
       [25, 25, 25,  4, 25]])

In [71]:
# Do the same thing with np.square()
np.square(random_array4)

array([[ 9, 49, 49, 36,  4],
       [ 0,  0,  4, 25, 36],
       [25, 25, 25,  4, 25]])

In [72]:
# Find the mean of the latest array using np.mean()
np.mean(random_array4)

4.0

In [73]:
# Find the maximum of the latest array using np.max()
np.max(random_array4)

7

In [76]:
# Find the minimum of the latest array using np.min()
np.min(random_array4)

0

In [77]:
# Find the standard deviation of the latest array
np.std(random_array4)

2.250925735484551

In [78]:
# Find the variance of the latest array
np.var(random_array4)

5.066666666666666

In [80]:
# Reshape the latest array to (3, 5, 1)
# np.reshape(random_array4,(3,5,1)) or 
random_array4.reshape(3,5,1)

array([[[3],
        [7],
        [7],
        [6],
        [2]],

       [[0],
        [0],
        [2],
        [5],
        [6]],

       [[5],
        [5],
        [5],
        [2],
        [5]]])

In [81]:
# Transpose the latest array
random_array4.T

array([[3, 0, 5],
       [7, 0, 5],
       [7, 2, 5],
       [6, 5, 2],
       [2, 6, 5]])

What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array5=np.random.randint(0,10,(3,3))
random_array6=np.random.randint(0,10,(3,2))

In [87]:
# Perform a dot product on the two newest arrays you created
random_array5.dot(random_array6)

array([[16, 24],
       [52, 64],
       [16, 29]])

In [88]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(0,10, size=(4, 3))
array2 = np.random.randint(0,10, size=(4, 3))

In [89]:
# Perform a dot product on the two newest arrays you created
np.dot(array1,array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [91]:
#Fixing above shaping problem
# For a matrix multiplication we need to satisfy matrix as (n,m)*(m,n) where m needs to be same(not necesserily n)
np.dot(array1,array2.T)

array([[ 11,  18,   8,  21],
       [102,  89,  96, 139],
       [119,  27, 119, 120],
       [ 88,  16,  89,  86]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [92]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1,array2

(array([[0, 2, 1],
        [8, 9, 5],
        [9, 2, 7],
        [7, 1, 5]]),
 array([[6, 1, 9],
        [1, 9, 0],
        [7, 0, 8],
        [5, 6, 9]]))

In [93]:
# Compare the two arrays with '>'
array1>array2

array([[False,  True, False],
       [ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [94]:
# Compare the two arrays with '>='
array1>=array2

array([[False,  True, False],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False, False]])

In [95]:
# Find which elements of the first array are greater than 7
array1>7

array([[False, False, False],
       [ True,  True, False],
       [ True, False, False],
       [False, False, False]])

In [96]:
# Which parts of each array are equal? (try using '==')
array1==array2

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [97]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[0, 1, 2],
       [5, 8, 9],
       [2, 7, 9],
       [1, 5, 7]])

In [98]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1)

array([[0, 2, 1],
       [2, 0, 1],
       [1, 2, 0],
       [1, 2, 0]])

In [99]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

4

In [100]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

0

In [101]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array1,axis=1)

array([1, 1, 0, 0])

In [102]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array1,axis=0)

array([0, 3, 0])

In [106]:
# Create an array of normally distributed random numbers
random_array7=np.random.randn(3,5)
random_array7

array([[-1.86726519,  0.68626019, -1.61271587, -0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478, -0.71530371,  0.67959775, -0.73036663],
       [ 0.21645859,  0.04557184, -0.65160035,  2.14394409,  0.63391902]])

In [103]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.